### ISSUE TITLE
iOS 10 minimum deployment target

### ISSUE THREAD

**Issue by dvkch** [GianniCarlo/DirectoryWatcher#1]
Hi,

I'm currently looking for Swiftier implementations of a directory watching solution, and yours seems to fit the bill! It's inspired from a library I forked a couple of years ago, which makes me really happy as the implementation details and current caveats will seem familiar. 

I was wondering about the iOS 10 minimum deployment target specified in the podspec. Was this made based on a technical point of view or was it an arbitrary decision? What about tvOS? 

I'm currently supporting iOS 9.0+ and tvOS 10.0+ and was wondering if modifying your podspec to cover those could be possible.

Thanks for considering, and for porting this great library to Swift :)

**Comment by GianniCarlo** [comment]
Hi @dvkch ! 

mmmm I think I updated the deployment target because my other [open source project](https://github.com/TortugaPower/BookPlayer) (an audiobook player) used some CoreData functions that are only available from iOS 10+. I remember I had problems with Carthage and the minimum deployment target, and out of laziness, I just updated the deployment target on this dependency.

I got my hands full today, but I'll be able to look into this tomorrow and see if I lower the target on this project.

**Comment by GianniCarlo** [comment]
One thing that I expanded upon from the original Objective-C concept, is the new listeners:
```
watcher.onNewFiles = { newFiles in
  // Files have been added
}

watcher.onDeletedFiles = { deletedFiles in
  // Files have been deleted
}
```

I had to add the difference, because in the audiobook player we were having an unintended consequence of trying to import things when a file was deleted (or something along those lines)

**Comment by GianniCarlo** [comment]
please let me know if you have any other request for this library. As it is, it fits my needs, but I wouldn't mind expanding on the functionality

**Comment by GianniCarlo** [comment]
@dvkch I updated the project's minimum deployment target and the podspec to `9.0`. It should be available in v2.3.0 for Cocoapods.

Regarding tvOS, I haven't actually done any development on that platform, so I'm not sure if just adding a dynamic framework that utilizes the existing files would work. You're welcome to open a pull request adding support for tvOS 👌

**Comment by dvkch** [comment]
Thanks a lot! I can confirm this works :) For tvOS I'll send a PR your way as soon as I've been able to start work on it. I think the available frameworks are similar enough to iOS to work with the same code, and it should just be a matter of declaring availability in the podspec. 

I saw your additions, this was the reason I forked the original project in the first place, I needed a quick way to know added / removed files as the original block doesn't report it. I had also added:

- a property containing polled files, while observing for new changes, before they are reported as added. it allowed me to ignore them when listing the contents of the directory in another part of my code

- when a directory is added I'd create a subdirectory watcher to observe it too, with a max depth

Those are obviously not requests, just ideas if you wanna iterate some day.

Thanks again!

**Comment by GianniCarlo** [comment]
I'm glad to hear it works! and thanks for the recommendations 👌, I think the first one should be pretty straightforward, I already got a private property called `previousContents` which should be the polled files 🤔

https://github.com/GianniCarlo/DirectoryWatcher/blob/07806228632421f1c991b02854588dac1e57d648/DirectoryWatcher/DirectoryWatcher.swift#L143-L149

I'm looking forward to your PR 👍
