### ISSUE TITLE
DirectoryDeepWatcher not included when installing via Cocoapods

### ISSUE THREAD

**Issue by DarioAhdoot** [GianniCarlo/DirectoryWatcher#4]
Installing latest version (2.4.0), I only see DirectoryWatcher.h and .swift in the Pod directory, not DirectoryDeepWatcher.swift. I inspected your podspec file and it seems correct. Any idea what is going on there?

**Comment by GianniCarlo** [comment]
Thanks for the heads-up, I forgot to publish the new version to Cocoapods. Will do asap 👌

**Comment by GianniCarlo** [comment]
version 2.5.0 should be published now @Diarrhio , please try again and reopen the ticket if its not working 👍

**Comment by DarioAhdoot** [comment]
That worked, thanks!
