### ISSUE TITLE
Feature Request: Ability for DirectoryDeepWatcher to automatically add new directories

### ISSUE THREAD

**Issue by DarioAhdoot** [GianniCarlo/DirectoryWatcher#5]
I like the DirectoryDeepWatcher because it automatically observes a tree of directories. Unfortunately, once observing has started, if a new directory is created in the sub-tree, the new directory will not be monitored. A workaround is to call `resetWatching` though it would be nice if the class automatically started monitoring those as well.

**Comment by GianniCarlo** [comment]
mmmmm true 🤔, this should be relatively easy 🤔

https://github.com/GianniCarlo/DirectoryWatcher/blob/de4b9aa0bf0b9d35c1d74255a436a26f8dbe9e34/DirectoryWatcher/DirectoryDeepWatcher.swift#L77-L80

In this completion handler, after we trigger the callback of the event, the simpler route would be to call `resetWatching`, although not sure how would that affect if we're expecting multiple notifications at the same time 🤔. 

The other option would be to instead create a file enumerator object from the folder URL in the notification, and call `self.startWatching(with: enumerator)`, and that will add watchers for the subtree of the folder. The only thing here to keep in mind, would be to avoid registering double listeners for other folders in the same subtree, so I would add the URL to the `SourceObject` alias, so the array can be checked inside `self.startWatching` to find out if the URL is already watched and skip to the next one

**Comment by GianniCarlo** [comment]
This may come in handy for my other project [BookPlayer](https://github.com/TortugaPower/BookPlayer), we're still in the process of revamping the file structure there, so once I can take up that task again, I'll look into making these changes 👍. Thanks for the feedback @Diarrhio , let me know if you got any more 💪

**Comment by DarioAhdoot** [comment]
> The other option would be to instead create a file enumerator object from the folder URL in the notification, and call self.startWatching(with: enumerator), and that will add watchers for the subtree of the folder. The only thing here to keep in mind, would be to avoid registering double listeners for other folders in the same subtree, so I would add the URL to the SourceObject alias, so the array can be checked inside self.startWatching to find out if the URL is already watched and skip to the next one

I think that's probably the way to go. I wish the OS event handler gave more information about what changed

**Comment by GianniCarlo** [comment]
solved in 2c25ecbc4b18e0215a8e32a2a768f5c3bcda60a7 and published in Cocoapods as v2.6.0, let me know when you get to test it @Diarrhio
